<a href="https://colab.research.google.com/github/adityaRakhecha/secure-and-private-ai-scholarship-challenge/blob/master/Lesson-3/lesson3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import torch

# number of entries in our database
num_entries = 5000

# create raw database
db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8)

**Generate Parallel Databases**

In [27]:
db[0:5]

tensor([1, 0, 0, 1, 0], dtype=torch.uint8)

In [0]:
remove_index = 2

In [0]:
# function to generate a parallel database with one entry removed
def get_parallel_db(db, remove_index):
  
  return torch.cat((db[0:remove_index],
                    db[remove_index+1:]))

In [30]:
get_parallel_db(db,2).shape

torch.Size([4999])

In [0]:
# function to generate parallel databases with one entry removed from each of the entries
def get_parallel_dbs(db):
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs

In [0]:
pdbs = get_parallel_dbs(db)

In [33]:
len(pdbs)

5000

In [0]:
# function to create and generate parallel databases
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [36]:
pdbs

[tensor([1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,